### ISSUE TITLE
Second index after FIVRVoltage

### ISSUE THREAD

**Issue by ngoonee** [mihic/linux-intel-undervolt#1]
In your guide you have:-

"The second number after FIVRVoltage is another index which I don't really know what it means"

Pretty sure that number is the ThrottleStop Profile. The fact that for you it is '2' all the time means you have the 3rd profile (by default that's called 'Internet') selected. In my case it was '0' all the time, as I'm just altering the initial 'Performance' profile.

Just thought I'd mention that, and this seemed the best place rather than the notebookreview forum thread.

**Comment by mihic** [comment]
Fixed, thanks!
