### ISSUE TITLE
Any chance of an all in one utility to do this?

### ISSUE THREAD

**Issue by oscardssmith** [mihic/linux-intel-undervolt#2]
I first want to congratulate you on the work you've done. It's really impressive. It would be really nice though if there was a program that was able to do this instead of needing to manually tweak offsets and stuff. I would be happy to help make this, although I do not fully understand the process yet (I am trying to follow the instructions, but I don't think it's working).

**Comment by georgewhewell** [comment]
Hi, i created a tool for this: https://github.com/georgewhewell/undervolt
If you use NixOS, you can apply undervolt automatically like so: https://github.com/georgewhewell/nixos-host/commit/0fefc23c5b498e81a71b1ee06fb82136f71c49f8

I second your thanks to @mihic, really great job!

**Comment by oscardssmith** [comment]
Thank you so much!!!! I'll try it out now. What hardware have you tested it on so far?

**Comment by georgewhewell** [comment]
I tested on my Lenovo X1 Yoga with i7-7600U. -135mV on core/cache, -75mV on gpu.

**Comment by tiziw** [comment]
I also made a utility for easy undervolting, mine is in bash tho. https://github.com/tiziw/iuvolt Good job tho george, mine is a bit of a hack compared to yours :P.

**Comment by kitsunyan** [comment]
Probably, it's too late to post yet another utility here, but I made it a long time ago. https://github.com/kitsunyan/intel-undervolt. This tool uses config file only and works as systemd service. It also allows to change temperature and power limits, so now it's not undervolting-only tool.

This tool requires a proper installation (and packaging, ideally).
