### ISSUE TITLE
cannot read or write MSR 0x00000150

### ISSUE THREAD

**Issue by miku86** [mihic/linux-intel-undervolt#3]
```
$ sudo apt-get install msr-tools
$ sudo rdmsr 0x150
rdmsr: CPU 0 cannot read MSR 0x00000150
$ sudo wrmsr 0x150 0x8000001000000000
wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x8000001000000000
$ sudo wrmsr 0x150 0x80000011F9A00000
wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000011f9a00000
```

i5-3320M  Ivy Bridge
Ubuntu 16.04 LTS

**Comment by mihic** [comment]
From the disclaimer:

> This is applicable to all Intel CPUs with an integrated voltage controller (FIVR). In general this includes all mobile Haswell and newer CPUs. I only tested this on one machine, a laptop with a i7-6700HQ.

I will try to make that sentence clearer, but Ivy Bridge is NOT supported.

**Comment by miku86** [comment]
Thanks and sorry for not getting this information.
